version: '3'
services:
  lib_db:
    image: postgres:14.5
    container_name: lib_db
    environment:
      POSTGRES_DB: IVASHCHENKO_215
      POSTGRES_USER: IVASHCHENKO_215
      POSTGRES_PASSWORD: IVASHCHENKO_215
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  trains_db:
    image: postgres:14.5
    container_name: trains_db
    environment:
      POSTGRES_DB: IVASHCHENKO_215
      POSTGRES_USER: IVASHCHENKO_215
      POSTGRES_PASSWORD: IVASHCHENKO_215
    volumes:
      - ./docker/db/scripts/trains:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  hospital_db:
    image: postgres:14.5
    container_name: hospital_db
    environment:
      POSTGRES_DB: IVASHCHENKO_215
      POSTGRES_USER: IVASHCHENKO_215
      POSTGRES_PASSWORD: IVASHCHENKO_215
    volumes:
      - ./docker/db/scripts/hospital:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"